### ISSUE TITLE
How to configure nginx?

### ISSUE THREAD

**Issue by phirumtan** [peterwvj/nextcloud#3]
HI, 
i have default port 80 using with website.
I don't know how to configure with nginx-proxy port 83:83 with nextcloud port 8383:80.

May you show me the config file.

Thanks in advance

**Comment by peterwvj** [comment]
Hi @phirumtan are you saying you already run an existing website on your server and that you also want to run this Nextcloud setup? If your website is running in a container you could try make it run on a port different than 80 and specify `VIRTUAL_HOST`, `VIRTUAL_NETWORK`,  and `LETSENCRYPT_HOST` to make it work with this setup with the `nextcloud-proxy-tier` network. If that isn't an option, I think you'd need to change the port numbers to meet your needs by editing the `docker-compose.yml` file. Did you try to change the `proxy` port mapping to meet your needs? Also, if you change the Nextcloud website port you might also want to set `VIRTUAL_PORT` for that container.

It's difficult to provide helpful input without knowing exactly what your setup looks like. Perhaps you're better off raising these kinds of questions on Stackoverflow. Also, I think it would be good if you could share the things you've tried in order to get it to work. You should probably also share your `docker-compose.file`.

**Comment by phirumtan** [comment]
@peterwvj got it.
i will provide the solution if i do it work.

Thanks 

good luck
